---
:verbose: false
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
development:
  :concurrency: 5
devtest:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:timeout: 30
:queues:
  - default
